name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MODERN: 0
  COMPARE: 1
  GAME_VERSION: FIRERED
  GAME_LANGUAGE: ENGLISH
  GAME_REVISION: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          repository: pret/agbcc
          path: agbcc

      - name: Checkout symbols branch from own repo
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@main
        with:
          ref: symbols
          path: symbols

      - name: Install dependencies
        run: sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev zip

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Compare FireRed
        run: |
          make -j$(nproc) all syms

      - name: Compare FireRed rev1
        env:
          GAME_REVISION: 1
        run: |
          make -j$(nproc) all syms

      - name: Compare LeafGreen
        env:
          GAME_VERSION: LEAFGREEN
        run: |
          make -j$(nproc) all syms

      - name: Compare LeafGreen rev1
        env:
          GAME_VERSION: LEAFGREEN
          GAME_REVISION: 1
        run: |
          make -j$(nproc) all syms

      - name: Build Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j$(nproc) all

      - name: Zip all .gba files
        run: zip -r gba_files.zip *.gba

      - name: Upload .gba artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: gba-files
          path: gba_files.zip
          if-no-files-found: error

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          cp *.sym symbols/
          echo "SYMBOLS_COMMIT_MSG=$( git log --format=%s ${GITHUB_SHA} )" >> $GITHUB_ENV

      - name: Update symfiles
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v7
        with:
          branch: symbols
          cwd: "./symbols"
          add: "*.sym"
          message: ${{ env.SYMBOLS_COMMIT_MSG }}
          push: true
          github_token: ${{ secrets.PAT_PUSH }}
